version: "3"

services:
  dbservice:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"  # Use double quotes around the value
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - order-system

  ordersystemservice:
    build:
      context: ./
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/docker?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - "9091:9091"
    networks:
      - order-system

networks:
  order-system:

volumes:
  db_data: